library(glmnet)
mydata = read.table("../../../../TrainingSet/FullSet/Lasso/bone.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mse",alpha=0.1,family="gaussian",standardize=FALSE)
sink('./bone_026.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
