library(glmnet)
mydata = read.table("../../../../TrainingSet/FullSet/ReliefF/lung_other.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mae",alpha=0.04,family="gaussian",standardize=TRUE)
sink('./lung_other_019.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
